/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import service.HoaDonChiTietBanHangService;
import service.ImeiBanHangService;
import service.ImeiService;
import service.SanPhamService;
import service.impl.HoaDonChiTietBanHangServiceIplm;
import service.impl.ImeiBanHangServiceIplm;
import service.impl.ImeiServiceImpl;
import service.impl.SanPhamServiceImpl;
import static view.FormBanHang.hdct;
import viewModel.HoaDonChiTietBanHangViewModel;
import viewModel.ImeiBanHang;
import viewModel.ImeiViewModel;

/**
 *
 * @author Dell
 */
public class FormImeiGioHang extends javax.swing.JFrame {

    /**
     * Creates new form FormImeiGioHang
     */
    private HoaDonChiTietBanHangService hdctSer = new HoaDonChiTietBanHangServiceIplm();
    private SanPhamService sps = new SanPhamServiceImpl();
    private ImeiBanHangService imeiSer = new ImeiBanHangServiceIplm();
    private ImeiService imeiSer1 = new ImeiServiceImpl();
    private ArrayList<ImeiViewModel> list = new ArrayList<>();
    public ArrayList<HoaDonChiTietBanHangViewModel> hdct = FormBanHang.hdct;
    
    public FormImeiGioHang() {
        initComponents();
        setLocationRelativeTo(null);
//        loadTable(imeiSer.getAllImei5(FormBanHang.maSp1));
        loadTable(imeiSer.getAllImeiKT(FormBanHang.maHD, FormBanHang.maSp1));
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setTitle("Chọm IMEI xóa.");
    }
    
    private void loadTable(ArrayList<ImeiViewModel> list) {
        DefaultTableModel model = (DefaultTableModel) tblImei.getModel();
        model.setRowCount(0);
        for (ImeiViewModel x : list) {
            model.addRow(new Object[]{x.getMaImei()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblImei = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblImei.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "MÃ IMEI"
            }
        ));
        tblImei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblImeiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblImeiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblImei);

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(btnOk))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        if (tblImei.getRowCount() > 1) {
            if (tblImei.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Mời chọn imei");
            } else {
                hdctSer.deleteHDCT(tblImei.getValueAt(tblImei.getSelectedRow(), 0).toString());
                imeiSer.deleteImeiKT(tblImei.getValueAt(tblImei.getSelectedRow(), 0).toString());
                imeiSer1.updateTT0(tblImei.getValueAt(tblImei.getSelectedRow(), 0).toString());
//                for (ImeiViewModel x : list) {
//                    imeiSer1.updateTT0(x.getMaImei());
//                }
                sps.addSlSp(FormBanHang.maSp1);
//                hdctSer.updateTruSoLuongSanPhamHDCT(FormBanHang.maSp1,FormBanHang.maHD, 1);
                JOptionPane.showMessageDialog(this, "ok");
                this.dispose();
            }
        } else {
            if (tblImei.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Mời chọn imei");
            } else {
                for (ImeiViewModel x : list) {
                    imeiSer1.updateTT0(x.getMaImei());
                }
                sps.addSlSp(FormBanHang.maSp1);
                hdctSer.xoaSanPhamTrongHDCT(FormBanHang.maSp1, FormBanHang.maHD);
                JOptionPane.showMessageDialog(this, "ok");
                this.dispose();
            }
        }
//        int soLuongXoa = tblImei.getRowCount();
//        if (soLuongXoa > 1) {
//            // khi số luọng nhập vào để xoá = số lượng sản phẩm trong giỏ hàng
//            //cập nhật lại số lượng sản phẩm trong bảng sản phẩm
//            sanPhamService.updateQuantity1(tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 1).toString(), soLuongXoa);
//
//            // xoá số sản phẩm khi số lượng nhập vào để xoá = số lượng sản phẩm đó trong giỏ hàng được chọn
//            hoaDonChiTietBanHangServices.xoaSanPhamTrongHDCT(tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 1).toString(), txtMaHD.getText().trim());
//
//        } else if (soLuongXoa < Integer.parseInt(tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 3).toString())) {
//            // khi số luọng nhập vào để xoá < số lượng sản phẩm trong giỏ hàng
//            //cập nhật lại số lượng sản phẩm trong bảng sản phẩm 
//            sanPhamService.updateQuantity1(tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 1).toString(), soLuongXoa);
//
//            // cập nhật lại số lượng sản phẩm trong giỏ hàng 
//            hoaDonChiTietBanHangServices.updateTruSoLuongSanPhamHDCT(
//                    tblDonHang.getValueAt(tblDonHang.getSelectedRow(), 1).toString(),
//                    txtMaHD.getText().trim(), soLuongXoa);
//        } else {
//            JOptionPane.showMessageDialog(this, "* Xoá thất bại\n-Số lượng nhập vào không đươc\n vượt quá số lượng hiện có", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
//            return;
//        }


    }//GEN-LAST:event_btnOkActionPerformed

    private void tblImeiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblImeiMouseClicked
        // TODO add your handling code here:
        HoaDonChiTietBanHangViewModel hd = new HoaDonChiTietBanHangViewModel();
        ImeiViewModel im = new ImeiViewModel();
        im.setMaImei(tblImei.getValueAt(tblImei.getSelectedRow(), 0).toString());
        list.add(im);
        for (HoaDonChiTietBanHangViewModel hd1 : hdct) {
            hd.setMaSanPham(FormBanHang.maSp1);
            hd.setTenSanPham(FormBanHang.tenSp);
            hd.setSoLuong(hd1.getSoLuong() - tblImei.getSelectedRow());
            hd.setDonGia(hd1.getDonGia());
        }
        boolean isCheck = false;
        for (HoaDonChiTietBanHangViewModel viewHoaDonChiTiet : hdct) {
            if (viewHoaDonChiTiet.getMaSanPham().equals(hd.getMaSanPham())) {
                viewHoaDonChiTiet.increaseQuantity1(hd.increaseQuantity1(0));
                isCheck = true;
            }
        }
        if (!isCheck) {
            hdct.add(hd);
        }
    }//GEN-LAST:event_tblImeiMouseClicked

    private void tblImeiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblImeiMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblImeiMousePressed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblImei.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(model);
        tblImei.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(txtTimKiem.getText().toUpperCase()));
    }//GEN-LAST:event_txtTimKiemKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormImeiGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormImeiGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormImeiGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormImeiGioHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormImeiGioHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblImei;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
