/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.lowagie.text.Row;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.HoaDon;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.HoaDonService;
import service.ThongKeService;
import service.impl.HoaDonServiceImpl;
import service.impl.ThongKeServiceImpl;
import viewModel.ThongKeKhachHangViewModel;
import viewModel.ThongKeNhanVienViewModel;
import viewModel.ThongKeSanPhamViewModel;

/**
 *
 * @author phamtuyetnga
 */
public class FormThongKe extends javax.swing.JPanel {

    private final HoaDonService hoaDonSer = new HoaDonServiceImpl();
    private final ThongKeService thongke = new ThongKeServiceImpl();

    /**
     * Creates new form FormThongKe
     */
    public FormThongKe() {
        initComponents();
        loadLblDtHn();
        loadLblHdCttHn();
        loadLblHdDttHn();
        loadLblSlHdHn();
        loadLblSlHdThang();
        loadLblHdDttThang();
        loadLblHdCttThang();
        loadLblDtThang();
        loadLblSlHdNam();
        loadLblHdDttNam();
        loadLblHdCttNam();
        loadLblDtNam();
        loadtable1();
        loadtable2();
        loadtable3();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDoanhThuHomNay = new javax.swing.JTextField();
        txtDoanhThuHomNay1 = new javax.swing.JTextField();
        txtDoanhThuHomNay2 = new javax.swing.JTextField();
        lblSoDon = new javax.swing.JLabel();
        lblDonDaThanhToan = new javax.swing.JLabel();
        lblDonChuaThanhToan = new javax.swing.JLabel();
        lblTongDoanhThu = new javax.swing.JLabel();
        tabSanPham = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblkhachhang = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDoanhThuHomNay6 = new javax.swing.JTextField();
        txtDoanhThuHomNay7 = new javax.swing.JTextField();
        txtDoanhThuHomNay8 = new javax.swing.JTextField();
        lblSoDon2 = new javax.swing.JLabel();
        lblDonDaThanhToan2 = new javax.swing.JLabel();
        lblDonChuaThanhToan2 = new javax.swing.JLabel();
        lblTongDoanhThu2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtDoanhThuHomNay9 = new javax.swing.JTextField();
        txtDoanhThuHomNay10 = new javax.swing.JTextField();
        txtDoanhThuHomNay11 = new javax.swing.JTextField();
        lblSoDon3 = new javax.swing.JLabel();
        lblDonDaThanhToan3 = new javax.swing.JLabel();
        lblDonChuaThanhToan3 = new javax.swing.JLabel();
        lblTongDoanhThu3 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(158, 195, 192));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DOANH THU - BÁO CÁO");

        jPanel2.setBackground(new java.awt.Color(255, 204, 0));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("DOANH THU HÔM NAY");

        txtDoanhThuHomNay.setBackground(new java.awt.Color(255, 204, 0));
        txtDoanhThuHomNay.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDoanhThuHomNay.setText("ĐẪ THANH TOÁN HÔM NAY:");
        txtDoanhThuHomNay.setBorder(null);
        txtDoanhThuHomNay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoanhThuHomNayActionPerformed(evt);
            }
        });

        txtDoanhThuHomNay1.setBackground(new java.awt.Color(255, 204, 0));
        txtDoanhThuHomNay1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDoanhThuHomNay1.setText("ĐƠN CHỜ THANH TOÁN HÔM NAY:");
        txtDoanhThuHomNay1.setBorder(null);
        txtDoanhThuHomNay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoanhThuHomNay1ActionPerformed(evt);
            }
        });

        txtDoanhThuHomNay2.setBackground(new java.awt.Color(255, 204, 0));
        txtDoanhThuHomNay2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDoanhThuHomNay2.setText("TỔNG SỐ ĐƠN HÔM NAY:");
        txtDoanhThuHomNay2.setBorder(null);

        lblSoDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoDon.setText("jLabel3");

        lblDonDaThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDonDaThanhToan.setText("jLabel3");

        lblDonChuaThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDonChuaThanhToan.setText("jLabel3");

        lblTongDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongDoanhThu.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDoanhThuHomNay2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoDon, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDoanhThuHomNay1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDonChuaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDoanhThuHomNay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDonDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuHomNay2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoDon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuHomNay, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonDaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuHomNay1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonChuaThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabSanPham.setBackground(new java.awt.Color(255, 255, 255));

        tblkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Họ và tên", "SĐT", "Ngày sinh", "Địa chỉ", "Giới tính", "Số lần mua", "Số điểm"
            }
        ));
        jScrollPane2.setViewportView(tblkhachhang);

        tabSanPham.addTab("Khách hàng", jScrollPane2);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ tên", "Email", "SDT", "Giới tính", "Ngày bắt đầu LV", "Chức vụ"
            }
        ));
        jScrollPane3.setViewportView(tblNhanVien);

        tabSanPham.addTab("Nhân Viên", jScrollPane3);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP", "Giá bán", "Số lượng tồn", "Trạng thái", "Đã bán", "Giá nhập", "Số tiền lãi"
            }
        ));
        jScrollPane4.setViewportView(tblSanPham);

        tabSanPham.addTab("Sản Phẩm", jScrollPane4);

        jPanel4.setBackground(new java.awt.Color(255, 204, 0));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setText("DOANH THU THÁNG");

        txtDoanhThuHomNay6.setBackground(new java.awt.Color(255, 204, 0));
        txtDoanhThuHomNay6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDoanhThuHomNay6.setText("ĐẪ THANH TOÁN THÁNG:");
        txtDoanhThuHomNay6.setBorder(null);
        txtDoanhThuHomNay6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoanhThuHomNay6ActionPerformed(evt);
            }
        });

        txtDoanhThuHomNay7.setBackground(new java.awt.Color(255, 204, 0));
        txtDoanhThuHomNay7.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDoanhThuHomNay7.setText("ĐƠN CHỜ THANH TOÁN THÁNG:");
        txtDoanhThuHomNay7.setBorder(null);
        txtDoanhThuHomNay7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoanhThuHomNay7ActionPerformed(evt);
            }
        });

        txtDoanhThuHomNay8.setBackground(new java.awt.Color(255, 204, 0));
        txtDoanhThuHomNay8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDoanhThuHomNay8.setText("TỔNG SỐ ĐƠN THÁNG:");
        txtDoanhThuHomNay8.setBorder(null);

        lblSoDon2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoDon2.setText("jLabel3");

        lblDonDaThanhToan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDonDaThanhToan2.setText("jLabel3");

        lblDonChuaThanhToan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDonChuaThanhToan2.setText("jLabel3");

        lblTongDoanhThu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongDoanhThu2.setText("jLabel3");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtDoanhThuHomNay8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoDon2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongDoanhThu2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtDoanhThuHomNay7, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDonChuaThanhToan2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtDoanhThuHomNay6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDonDaThanhToan2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuHomNay8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoDon2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuHomNay6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonDaThanhToan2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuHomNay7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonChuaThanhToan2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblTongDoanhThu2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 0));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel10.setText("DOANH THU NĂM");

        txtDoanhThuHomNay9.setBackground(new java.awt.Color(255, 204, 0));
        txtDoanhThuHomNay9.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDoanhThuHomNay9.setText("ĐẪ THANH TOÁN NĂM:");
        txtDoanhThuHomNay9.setBorder(null);
        txtDoanhThuHomNay9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoanhThuHomNay9ActionPerformed(evt);
            }
        });

        txtDoanhThuHomNay10.setBackground(new java.awt.Color(255, 204, 0));
        txtDoanhThuHomNay10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDoanhThuHomNay10.setText("ĐƠN CHỜ THANH TOÁN:");
        txtDoanhThuHomNay10.setBorder(null);

        txtDoanhThuHomNay11.setBackground(new java.awt.Color(255, 204, 0));
        txtDoanhThuHomNay11.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        txtDoanhThuHomNay11.setText("TỔNG SỐ ĐƠN NĂM:");
        txtDoanhThuHomNay11.setBorder(null);

        lblSoDon3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSoDon3.setText("jLabel3");

        lblDonDaThanhToan3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDonDaThanhToan3.setText("jLabel3");

        lblDonChuaThanhToan3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDonChuaThanhToan3.setText("jLabel3");

        lblTongDoanhThu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongDoanhThu3.setText("jLabel3");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtDoanhThuHomNay11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoDon3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTongDoanhThu3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtDoanhThuHomNay10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDonChuaThanhToan3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtDoanhThuHomNay9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDonDaThanhToan3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuHomNay11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoDon3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuHomNay9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonDaThanhToan3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDoanhThuHomNay10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonChuaThanhToan3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblTongDoanhThu3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 1218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(tabSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void loadtable1() {
        ArrayList<ThongKeKhachHangViewModel> listkh = thongke.getAll();
        DefaultTableModel model = (DefaultTableModel) tblkhachhang.getModel();
        for (ThongKeKhachHangViewModel x : listkh) {
            model.addRow(new Object[]{
                x.getMaKH(),
                x.getHoTen(),
                x.getSdt(),
                x.getNgaySinh(),
                x.getDiaChi(),
                x.getGioiTinh() == 1 ? "Nam" : "Nữ",
                x.getSoLanMua(),
                x.getSoDiem()
            });
        }
    }

    public void loadtable2() {
        ArrayList<ThongKeNhanVienViewModel> listnv = thongke.getAllNV();
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        for (ThongKeNhanVienViewModel x : listnv) {
            model.addRow(new Object[]{
                x.getMaNV(),
                x.getHoVaTen(),
                x.getEmail(),
                x.getSDT(),
                x.getGioiTinh() == 1 ? "Nam" : "Nữ",
                x.getNgayBatDauLV(),
                x.getChucVu()});
        }
    }

    public void loadtable3() {
        int i = 1;
        ArrayList<ThongKeSanPhamViewModel> listsp = thongke.getAll2();
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        for (ThongKeSanPhamViewModel x : listsp) {
            model.addRow(new Object[]{
                i++,
                x.getMaSP(),
                x.getTenSP(),
                x.getGiaBan(),
                x.getSoLuongTon(),
                x.getTrangThai(),
                x.getDaBan(),
                x.getGiaNhap(),
                x.getTienLai()});
        }
    }

    public void loadLblSlHdHn() {
        for (HoaDon hd : hoaDonSer.soLuongHD()) {
            lblSoDon.setText(hd.getMaHD());
        }
    }

    public void loadLblHdDttHn() {
        for (HoaDon hd : hoaDonSer.soDonDaTT()) {
            lblDonDaThanhToan.setText(hd.getMaHD());
        }
    }

    public void loadLblHdCttHn() {
        for (HoaDon hd : hoaDonSer.soDonChuaTT()) {
            lblDonChuaThanhToan.setText(hd.getMaHD());
        }
    }

    public void loadLblDtHn() {
        for (HoaDon hd : hoaDonSer.getDoanhThu()) {
            lblTongDoanhThu.setText(String.valueOf(hd.getTongTien()));
            String[] splits = lblTongDoanhThu.getText().split(".0000$");
            StringBuilder stringBuilder1 = new StringBuilder();
            for (String x : splits) {
                stringBuilder1.append(x);
            }
            lblTongDoanhThu.setText(stringBuilder1.toString() + " VNĐ");
        }
    }

    private void txtDoanhThuHomNayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoanhThuHomNayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoanhThuHomNayActionPerformed
    private void xuatExcel() {
        try {
            XSSFWorkbook workbook1 = new XSSFWorkbook();
            XSSFSheet spreadSheet1 = workbook1.createSheet("Hóa Đơn");

            XSSFRow row = null;
            Cell cell = null;
            row = spreadSheet1.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);

            cell.setCellValue("Danh Sách Khách Hàng");

            row = spreadSheet1.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("MaKH");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Họ tên");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("SĐT");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Ngày Sinh");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Địa Chỉ");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Giới tính");
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Số lần mua");
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("Số điểm");
            List<ThongKeKhachHangViewModel> list = thongke.getAll();

            for (int i = 0; i < list.size(); i++) {
                ThongKeKhachHangViewModel model = list.get(i);
                row = spreadSheet1.createRow((short) 4 + i);
                row.setHeight((short) 400);
                row.createCell(0).setCellValue(model.getMaKH());
                row.createCell(1).setCellValue(model.getHoTen());
                row.createCell(2).setCellValue(model.getSdt());
                row.createCell(3).setCellValue(model.getNgaySinh());
                row.createCell(4).setCellValue(model.getDiaChi());
                row.createCell(5).setCellValue(model.getGioiTinh());
                row.createCell(6).setCellValue((model.getSoLanMua()));
                row.createCell(7).setCellValue(model.getSoDiem());
            }
            FileOutputStream out = new FileOutputStream(new File("F:\\ds.xlsx"));
            workbook1.write(out);
            out.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        //Nhân viên 
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadSheet = workbook.createSheet("Nhân Viên");

            XSSFRow row = null;
            Cell cell = null;
            row = spreadSheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);

            cell.setCellValue("Danh Sách Nhân Viên");

            row = spreadSheet.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Mã NV");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Họ tên");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Email");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("SDT");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Giới tính");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Ngày bắt đầu làm việc");
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Chức vụ");

            List<ThongKeNhanVienViewModel> list = thongke.getAllNV();

            for (int i = 0; i < list.size(); i++) {
                ThongKeNhanVienViewModel model = list.get(i);
                row = spreadSheet.createRow((short) 4 + i);
                row.setHeight((short) 400);
                row.createCell(0).setCellValue(model.getMaNV());
                row.createCell(1).setCellValue(model.getHoVaTen());
                row.createCell(2).setCellValue(model.getEmail());
                row.createCell(3).setCellValue(model.getSDT());
                row.createCell(4).setCellValue(model.getGioiTinh());
                row.createCell(5).setCellValue(model.getNgayBatDauLV());
                row.createCell(6).setCellValue((model.getChucVu()));

            }
            FileOutputStream out = new FileOutputStream(new File("F:\\ds.xlsx"));
            workbook.write(out);
            out.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void txtDoanhThuHomNay6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoanhThuHomNay6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoanhThuHomNay6ActionPerformed

    private void txtDoanhThuHomNay9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoanhThuHomNay9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoanhThuHomNay9ActionPerformed

    private void txtDoanhThuHomNay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoanhThuHomNay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoanhThuHomNay1ActionPerformed

    private void txtDoanhThuHomNay7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoanhThuHomNay7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoanhThuHomNay7ActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblkhachhang.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(model);
        tblkhachhang.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(txtTimKiem.getText().toUpperCase()));
        
        DefaultTableModel model1 = (DefaultTableModel) tblNhanVien.getModel();
        TableRowSorter<DefaultTableModel> trs1 = new TableRowSorter<DefaultTableModel>(model);
        tblNhanVien.setRowSorter(trs);
        trs1.setRowFilter(RowFilter.regexFilter(txtTimKiem.getText().toUpperCase()));
        
        DefaultTableModel model2 = (DefaultTableModel) tblSanPham.getModel();
        TableRowSorter<DefaultTableModel> trs2 = new TableRowSorter<DefaultTableModel>(model);
        tblSanPham.setRowSorter(trs);
        trs2.setRowFilter(RowFilter.regexFilter(txtTimKiem.getText().toUpperCase()));
    }//GEN-LAST:event_txtTimKiemKeyReleased

    public void loadLblSlHdThang() {
        for (HoaDon hd : hoaDonSer.getSoLuongHoaDonThang()) {
            lblSoDon2.setText(hd.getMaHD());
        }
    }

    public void loadLblHdDttThang() {
        for (HoaDon hd : hoaDonSer.getSoDonDaThanhToanThang()) {
            lblDonDaThanhToan2.setText(hd.getMaHD());
        }
    }

    public void loadLblHdCttThang() {
        for (HoaDon hd : hoaDonSer.getSoDonChuaThanhToanThang()) {
            lblDonChuaThanhToan2.setText(hd.getMaHD());
        }
    }

    public void loadLblDtThang() {
        for (HoaDon hd : hoaDonSer.getDoanhThuThang()) {
            lblTongDoanhThu2.setText(String.valueOf(hd.getTongTien()));
            String[] splits = lblTongDoanhThu2.getText().split(".0000$");
            StringBuilder stringBuilder1 = new StringBuilder();
            for (String x : splits) {
                stringBuilder1.append(x);
            }
            lblTongDoanhThu2.setText(stringBuilder1.toString() + " VNĐ");
        }
    }

    public void loadLblSlHdNam() {
        for (HoaDon hd : hoaDonSer.getSoLuongHoaDonNam()) {
            lblSoDon3.setText(hd.getMaHD());
        }
    }

    public void loadLblHdDttNam() {
        for (HoaDon hd : hoaDonSer.getSoDonDaThanhToanNam()) {
            lblDonDaThanhToan3.setText(hd.getMaHD());
        }
    }

    public void loadLblHdCttNam() {
        for (HoaDon hd : hoaDonSer.getSoDonChuaThanhToanNam()) {
            lblDonChuaThanhToan3.setText(hd.getMaHD());
        }
    }

    public void loadLblDtNam() {
        for (HoaDon hd : hoaDonSer.getDoanhThuNam()) {
            lblTongDoanhThu3.setText(String.valueOf(hd.getTongTien()));
            String[] splits = lblTongDoanhThu3.getText().split(".0000$");
            StringBuilder stringBuilder1 = new StringBuilder();
            for (String x : splits) {
                stringBuilder1.append(x);
            }
            lblTongDoanhThu3.setText(stringBuilder1.toString() + " VNĐ");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblDonChuaThanhToan;
    private javax.swing.JLabel lblDonChuaThanhToan2;
    private javax.swing.JLabel lblDonChuaThanhToan3;
    private javax.swing.JLabel lblDonDaThanhToan;
    private javax.swing.JLabel lblDonDaThanhToan2;
    private javax.swing.JLabel lblDonDaThanhToan3;
    private javax.swing.JLabel lblSoDon;
    private javax.swing.JLabel lblSoDon2;
    private javax.swing.JLabel lblSoDon3;
    private javax.swing.JLabel lblTongDoanhThu;
    private javax.swing.JLabel lblTongDoanhThu2;
    private javax.swing.JLabel lblTongDoanhThu3;
    private javax.swing.JTabbedPane tabSanPham;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTable tblkhachhang;
    private javax.swing.JTextField txtDoanhThuHomNay;
    private javax.swing.JTextField txtDoanhThuHomNay1;
    private javax.swing.JTextField txtDoanhThuHomNay10;
    private javax.swing.JTextField txtDoanhThuHomNay11;
    private javax.swing.JTextField txtDoanhThuHomNay2;
    private javax.swing.JTextField txtDoanhThuHomNay6;
    private javax.swing.JTextField txtDoanhThuHomNay7;
    private javax.swing.JTextField txtDoanhThuHomNay8;
    private javax.swing.JTextField txtDoanhThuHomNay9;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
