/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.FlowLayout;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.DangNhap;
import service.DangNhapService;
import service.impl.DangNhapServiceImpl;

/**
 *
 * @author phamtuyetnga
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public DangNhapService dangNhapService = new DangNhapServiceImpl();
    public static DangNhap dangNhap;
    private LoginGiaoCa LoginGiaoCa = new LoginGiaoCa();
    private Login1 Login1 = new Login1();

    public FormMenu() {
        initComponents();
        showButton();
        setTitle("PHẦN MỀM BÁN ĐIỆN THOẠI");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVoucher = new com.k33ptoo.components.KButton();
        btnKhachHang = new com.k33ptoo.components.KButton();
        btnSanPham = new com.k33ptoo.components.KButton();
        btnHoaDon = new com.k33ptoo.components.KButton();
        btnBanHang = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThongKe = new com.k33ptoo.components.KButton();
        btnNhanVien = new com.k33ptoo.components.KButton();
        jSeparator1 = new javax.swing.JSeparator();
        Panel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGiaoCa = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnGiaoCaTong = new javax.swing.JButton();
        btnQuyDoiDiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-voucher.png"))); // NOI18N
        btnVoucher.setText("GIẢM GIÁ");
        btnVoucher.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnVoucher.setkBackGroundColor(new java.awt.Color(53, 107, 102));
        btnVoucher.setkEndColor(new java.awt.Color(53, 107, 102));
        btnVoucher.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnVoucher.setkHoverForeGround(new java.awt.Color(53, 107, 102));
        btnVoucher.setkHoverStartColor(new java.awt.Color(53, 107, 102));
        btnVoucher.setkPressedColor(new java.awt.Color(53, 107, 102));
        btnVoucher.setkSelectedColor(new java.awt.Color(53, 107, 102));
        btnVoucher.setkStartColor(new java.awt.Color(53, 107, 102));
        btnVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoucherActionPerformed(evt);
            }
        });

        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-khachhang.png"))); // NOI18N
        btnKhachHang.setText("KHÁCH HÀNG");
        btnKhachHang.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnKhachHang.setkBackGroundColor(new java.awt.Color(53, 107, 102));
        btnKhachHang.setkEndColor(new java.awt.Color(53, 107, 102));
        btnKhachHang.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnKhachHang.setkHoverForeGround(new java.awt.Color(53, 107, 102));
        btnKhachHang.setkHoverStartColor(new java.awt.Color(53, 107, 102));
        btnKhachHang.setkPressedColor(new java.awt.Color(53, 107, 102));
        btnKhachHang.setkSelectedColor(new java.awt.Color(53, 107, 102));
        btnKhachHang.setkStartColor(new java.awt.Color(53, 107, 102));
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-sanpham.png"))); // NOI18N
        btnSanPham.setText("SẢN PHẨM");
        btnSanPham.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnSanPham.setkBackGroundColor(new java.awt.Color(53, 107, 102));
        btnSanPham.setkEndColor(new java.awt.Color(53, 107, 102));
        btnSanPham.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnSanPham.setkHoverForeGround(new java.awt.Color(53, 107, 102));
        btnSanPham.setkHoverStartColor(new java.awt.Color(53, 107, 102));
        btnSanPham.setkPressedColor(new java.awt.Color(53, 107, 102));
        btnSanPham.setkSelectedColor(new java.awt.Color(53, 107, 102));
        btnSanPham.setkStartColor(new java.awt.Color(53, 107, 102));
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-hoadon.png"))); // NOI18N
        btnHoaDon.setText("HOÁ ĐƠN");
        btnHoaDon.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnHoaDon.setkBackGroundColor(new java.awt.Color(53, 107, 102));
        btnHoaDon.setkEndColor(new java.awt.Color(53, 107, 102));
        btnHoaDon.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnHoaDon.setkHoverForeGround(new java.awt.Color(53, 107, 102));
        btnHoaDon.setkHoverStartColor(new java.awt.Color(53, 107, 102));
        btnHoaDon.setkPressedColor(new java.awt.Color(53, 107, 102));
        btnHoaDon.setkSelectedColor(new java.awt.Color(53, 107, 102));
        btnHoaDon.setkStartColor(new java.awt.Color(53, 107, 102));
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-banhang.png"))); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBanHang.setkBackGroundColor(new java.awt.Color(53, 107, 102));
        btnBanHang.setkEndColor(new java.awt.Color(53, 107, 102));
        btnBanHang.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnBanHang.setkHoverForeGround(new java.awt.Color(53, 107, 102));
        btnBanHang.setkHoverStartColor(new java.awt.Color(53, 107, 102));
        btnBanHang.setkIndicatorColor(new java.awt.Color(53, 107, 102));
        btnBanHang.setkPressedColor(new java.awt.Color(53, 107, 102));
        btnBanHang.setkSelectedColor(new java.awt.Color(53, 107, 102));
        btnBanHang.setkStartColor(new java.awt.Color(53, 107, 102));
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel2.setText("APPLE STORE");

        btnThongKe.setIcon(new javax.swing.ImageIcon("F:\\DuAn1\\Duan_hoanthienH\\src\\icons\\thongKe.png")); // NOI18N
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnThongKe.setkBackGroundColor(new java.awt.Color(53, 107, 102));
        btnThongKe.setkEndColor(new java.awt.Color(53, 107, 102));
        btnThongKe.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnThongKe.setkHoverForeGround(new java.awt.Color(53, 107, 102));
        btnThongKe.setkHoverStartColor(new java.awt.Color(53, 107, 102));
        btnThongKe.setkPressedColor(new java.awt.Color(53, 107, 102));
        btnThongKe.setkSelectedColor(new java.awt.Color(53, 107, 102));
        btnThongKe.setkStartColor(new java.awt.Color(53, 107, 102));
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons-nhanvien.png"))); // NOI18N
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnNhanVien.setkBackGroundColor(new java.awt.Color(53, 107, 102));
        btnNhanVien.setkEndColor(new java.awt.Color(53, 107, 102));
        btnNhanVien.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        btnNhanVien.setkHoverForeGround(new java.awt.Color(53, 107, 102));
        btnNhanVien.setkHoverStartColor(new java.awt.Color(53, 107, 102));
        btnNhanVien.setkPressedColor(new java.awt.Color(53, 107, 102));
        btnNhanVien.setkSelectedColor(new java.awt.Color(53, 107, 102));
        btnNhanVien.setkStartColor(new java.awt.Color(53, 107, 102));
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Panel1.setBackground(new java.awt.Color(158, 195, 192));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/applestore.jpg.png"))); // NOI18N

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(158, 195, 192));

        btnGiaoCa.setBackground(new java.awt.Color(255, 255, 0));
        btnGiaoCa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGiaoCa.setText("Giao Ca");
        btnGiaoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoCaActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(255, 102, 102));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnGiaoCaTong.setBackground(new java.awt.Color(0, 0, 0));
        btnGiaoCaTong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGiaoCaTong.setForeground(new java.awt.Color(255, 255, 255));
        btnGiaoCaTong.setText("QL GIAO CA");
        btnGiaoCaTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaoCaTongActionPerformed(evt);
            }
        });

        btnQuyDoiDiem.setBackground(new java.awt.Color(0, 0, 0));
        btnQuyDoiDiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuyDoiDiem.setForeground(new java.awt.Color(255, 255, 255));
        btnQuyDoiDiem.setText("QUY ĐỔI ĐIỂM");
        btnQuyDoiDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuyDoiDiemActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("APPLE STORE XIN CHÀO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGiaoCaTong, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuyDoiDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157)
                .addComponent(btnGiaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(1086, Short.MAX_VALUE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnGiaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnQuyDoiDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGiaoCaTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showButton(){
        if (LoginGiaoCa.checklogin == false) {
            if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Nhân Viên")) {
                btnGiaoCaTong.setVisible(false);
                btnQuyDoiDiem.setVisible(false);
                btnDangXuat.setVisible(false);
            } else if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Quản Lý")) {
                btnGiaoCaTong.setVisible(true);
                btnQuyDoiDiem.setVisible(true);
                btnDangXuat.setVisible(true);
            }
        } else {
            if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Nhân Viên")) {
                btnGiaoCaTong.setVisible(false);
                btnQuyDoiDiem.setVisible(false);
                btnDangXuat.setVisible(false);
            } else if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Quản Lý")) {
                btnGiaoCaTong.setVisible(true);
                btnQuyDoiDiem.setVisible(true);
                btnDangXuat.setVisible(true);
            }
        }
    }
    private void btnVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoucherActionPerformed
        if (LoginGiaoCa.checklogin == false) {
            if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Quản Lý")) {
                FormGiamGia sp = new FormGiamGia();
                Panel1.removeAll();
                Panel1.add(sp);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        } else {
            if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Quản Lý")) {
                FormGiamGia sp = new FormGiamGia();
                Panel1.removeAll();
                Panel1.add(sp);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnVoucherActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        if (LoginGiaoCa.checklogin == false) {
            if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Quản Lý")) {
                KhachHang kh = new KhachHang();
                Panel1.removeAll();
                Panel1.add(kh);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        } else {
            if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Quản Lý")) {
                KhachHang kh = new KhachHang();
                Panel1.removeAll();
                Panel1.add(kh);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        if (LoginGiaoCa.checklogin == false) {
            if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Quản Lý")) {
                FormNhanVien sp = new FormNhanVien();
                Panel1.removeAll();
                Panel1.add(sp);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        } else {
            if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Quản Lý")) {
                FormNhanVien sp = new FormNhanVien();
                Panel1.removeAll();
                Panel1.add(sp);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        if (LoginGiaoCa.checklogin == false) {
            if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(Login1.maNV).equals("Quản Lý")) {
                FormSanPham sp = new FormSanPham();
                Panel1.removeAll();
                Panel1.add(sp);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        } else {
            if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(LoginGiaoCa.maNV).equals("Quản Lý")) {
                FormSanPham sp = new FormSanPham();
                Panel1.removeAll();
                Panel1.add(sp);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        HoaDonn sp = new HoaDonn();
        Panel1.removeAll();
        Panel1.add(sp);
        Panel1.setLayout(new FlowLayout());
        this.pack();
        Panel1.setVisible(true);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        FormBanHang sp = new FormBanHang();
        Panel1.removeAll();
        Panel1.add(sp);
        Panel1.setLayout(new FlowLayout());
        this.pack();
        Panel1.setVisible(true);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        FormThongKe sp = new FormThongKe();
        Panel1.removeAll();
        Panel1.add(sp);
        Panel1.setLayout(new FlowLayout());
        this.pack();
        Panel1.setVisible(true);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnGiaoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoCaActionPerformed
        // TODO add your handling code here:
        new NhanVienGiaoCa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGiaoCaActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        if (LoginGiaoCa.checklogin == false) {
            if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                
                return;

            } else if (dangNhapService.checkTK(Login1.maNV).equals("Quản Lý")) {
                int luachon = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất không", "Xác nhận", JOptionPane.YES_NO_CANCEL_OPTION);
                if (luachon == JOptionPane.YES_OPTION) {
                    new LoginGiaoCa().setVisible(true);
                    dispose();
                }
            }
        } else {
            if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(LoginGiaoCa.maNV).equals("Quản Lý")) {
                int luachon = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất không", "Xác nhận", JOptionPane.YES_NO_CANCEL_OPTION);
                if (luachon == JOptionPane.YES_OPTION) {
                    new LoginGiaoCa().setVisible(true);
                    dispose();
                }
            }
        }


    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnGiaoCaTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaoCaTongActionPerformed
        // TODO add your handling code here:
        if (LoginGiaoCa.checklogin == false) {
            if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Quản Lý")) {
                GiaoCaForm sp = new GiaoCaForm();
                Panel1.removeAll();
                Panel1.add(sp);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        } else {
            if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Quản Lý")) {
                GiaoCaForm sp = new GiaoCaForm();
                Panel1.removeAll();
                Panel1.add(sp);
                Panel1.setLayout(new FlowLayout());
                this.pack();
                Panel1.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnGiaoCaTongActionPerformed

    private void btnQuyDoiDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuyDoiDiemActionPerformed
        // TODO add your handling code here:
        if (LoginGiaoCa.checklogin == false) {
            if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(Login1.maNV).equalsIgnoreCase("Quản Lý")) {
                new FormQuyDoiDiem().setVisible(true);
            }
        } else {
            if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Nhân Viên")) {
                JOptionPane.showMessageDialog(this, "Tài khoản ko có quyền truy cập");
                return;

            } else if (dangNhapService.checkTK(LoginGiaoCa.maNV).equalsIgnoreCase("Quản Lý")) {
                new FormQuyDoiDiem().setVisible(true);
            }
        }
    }//GEN-LAST:event_btnQuyDoiDiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private com.k33ptoo.components.KButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnGiaoCa;
    private javax.swing.JButton btnGiaoCaTong;
    private com.k33ptoo.components.KButton btnHoaDon;
    private com.k33ptoo.components.KButton btnKhachHang;
    private com.k33ptoo.components.KButton btnNhanVien;
    private javax.swing.JButton btnQuyDoiDiem;
    private com.k33ptoo.components.KButton btnSanPham;
    private com.k33ptoo.components.KButton btnThongKe;
    private com.k33ptoo.components.KButton btnVoucher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
