/*
............/´¯/)........... (\¯'\
............/....//........... ...\\....\
.........../....//............ ....\\....\
...../´¯/..../´¯\.........../¯ '\....\¯'\
.././.../..../..../.|_......_| .\....\....\...\.\..
(.(....(....(..../.)..)..(..(. \....)....)....).)
.\................\/.../....\. ..\/................/
..\................. /........\..................../
....\..............(.......... ..)................/           


 */
package view;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class QuetMaKhachHang extends javax.swing.JFrame implements Runnable, ThreadFactory {

    /**
     * Creates new form QuetMa
     */
    public QuetMaKhachHang() {
        initComponents();
        initWebCam();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

    }
    private WebcamPanel panel = null;
    private Webcam webcam = null;

    private static final long serial = 6441489157408381878L;
    private Executor ex = Executors.newSingleThreadExecutor(this);
    public static String hoTen = null;
    public static String ngaySinh = null;
    public static String diaChi = null;
    public static String gioiTinh = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtma = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnTroVe = new javax.swing.JButton();

        txtma.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTroVe.setIcon(new javax.swing.ImageIcon("F:\\DuAn1\\DuAn1_BackUp\\src\\icons\\signout_106525.png")); // NOI18N
        btnTroVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTroVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTroVe, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(btnTroVe)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTroVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTroVeActionPerformed
        KhachHang kh = new KhachHang();
                    kh.setVisible(true);
                    this.dispose();
                    webcam.close();
    }//GEN-LAST:event_btnTroVeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuetMaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuetMaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuetMaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuetMaKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuetMaKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTroVe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtma;
    // End of variables declaration//GEN-END:variables

    public void initWebCam() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        ex.execute(this);

    }

    @Override
    public void run() {
        do {

            try {
                Thread.sleep(100);

            } catch (Exception e) {
                System.out.println(e);
            }

            Result result = null;
            BufferedImage image = null;

            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }
            }
            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (Exception e) {
            }
            if (result != null) {

                try {

                    txtma.setText(result.getText());

                    String chuoi = txtma.getText();
                    String nganCach = "|";

                    int soCmt = chuoi.indexOf(nganCach); // lấy ra vị trí
                    String soCanCuocCongDan = chuoi.substring(0, soCmt);
////        txtSoCmt.setText(soCanCuocCongDan);

                    int soCMTCu = chuoi.indexOf(nganCach, soCmt + 1);// lấy ra vị trí
                    String sochungMinhThu = chuoi.substring(soCmt + 1, soCMTCu);
                    System.out.println(sochungMinhThu);
////     
//      
                    int hoTen1 = chuoi.indexOf(nganCach, soCMTCu + 1);// lấy ra vị trí
                    hoTen = chuoi.substring(soCMTCu + 1, hoTen1);

//        
//        String khoangTrang=" ";
//        
//          int ho=hoVaTen.indexOf(khoangTrang);
//        String ho1=hoVaTen.substring(0,ho);
//                System.out.println(ho1);
//                
//        txtHoTen.setText(hoVaTen);
//                
////      txtHoTen.setText(hoVaTen);
                    int ngaySinh1 = chuoi.indexOf(nganCach, hoTen1 + 1);// lấy ra vị trí
                    String ngaySinh2 = chuoi.substring(hoTen1 + 1, ngaySinh1);
                    SimpleDateFormat simDate = new SimpleDateFormat("dd-MM-yyyy");
                    String catNgaySinh = ngaySinh2.substring(0, 2);
                    String catThangSinh = ngaySinh2.substring(2, 4);
                    String catNamSinh = ngaySinh2.substring(4, 8);
                    ngaySinh = catNamSinh + "-" + catThangSinh + "-" + catNgaySinh;

                    System.out.println(QuetMaKhachHang.ngaySinh);

                    int i = chuoi.indexOf(nganCach, ngaySinh1 + 1);// lấy ra vị trí
                    gioiTinh = chuoi.substring(ngaySinh1 + 1, i);
                    System.out.println(gioiTinh);

////
                    int diaChi1 = chuoi.indexOf(nganCach, i + 1);// lấy ra vị trí
                    diaChi = chuoi.substring(i + 1, diaChi1);
                    System.out.println(diaChi);
//        txtDiaChi.setText(diaChi);
//        txtMaKhachHang.setText("");
                    JOptionPane.showMessageDialog(this, "Quét Mã Thành Công");
                   
                    return;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Quét Mã Thất Bại");
                    return;
                }

            }

        } while (true);
    }

    @Override
    public Thread newThread(Runnable r) {
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
    }
}
